# Sampled Dataset exploration, meta-data collection

In [1]:
# Imports go here
import os
import glob
import pandas as pd

**Depending on the mode that you wish to use, you need to start Spark differently**

We first show how to run it in local mode, then how to run it in cluster mode (yarn). Therefore, **only run 1 of the two next cells**

### Convenience functions

What follows are some functions to extract essential meta-data from the list of files in the dataset. Such as:
- the year of the trips data in the file
- the month
- the file size
- the number of records
- the (relational) schema of the file

In [2]:
def get_schema(filename):
    '''Extracts the schema from the given file
    
    Assumes that the first line of the file includes the schema
    '''
    with open(filename, 'r') as f:
        return tuple([attr.strip('" ').lower() for attr in f.readline().strip().split(',')])
      
def get_month(filename):
    '''Returns the month that the TCL file reports on.
    
       Assumes that the filename uses the TLC convensions:
       $(fileSource)_tripdata_$(year)-$(month).csv
    '''
    return int(filename[-6:-4])

def get_year(filename):
    '''Returns the month that the TCL file reports on. 
    
       Assumes that the filename uses the TLC convensions:
       $(fileSource)_tripdata_$(year)-$(month).csv
    '''
    #TODO: to be completed by you, cf the get_month function!
    return int(filename[-11:-7])

def get_type(filename):
    '''Returns the type of trip that the TCL file reports on (yellow, green, fhv, hvfhv). 
    
       Assumes that the filename uses the TLC convensions:
       $(fileSource)_tripdata_$(year)-$(month).csv
    '''
    #TODO: to be completed by you
    
    # The basename of the file is the file name without the folder information
    # E.g., if filename = "/home/stijn/foo.txt" then the basename = "foo.txt"
    basename = os.path.basename(filename)
    # compute the type here from the basename string
    transport_class = basename.split('_', 1)[0]
    return transport_class # To be replaced with the correct answer

def get_numrecords(filename):
    '''Returns the number of records in a TCL file.
       
       Equals the number of lines in the file minus one 
       (the header, which is the schema, not a record)
    '''
    with open(filename) as f:
        lines = 0
        for line in f:
            lines += 1
        return lines - 1                   
    
def get_metadata(filename):
    '''Returns all metadata associated to the `filename` datafile as one big tuple'''
    return (filename, 
            get_type(filename),
            get_year(filename),
            get_month(filename),
            os.path.getsize(filename),
            get_numrecords(filename),
            get_schema(filename) )

In [6]:
# NOTE: this cell actually reads 14 GB of data, so be patient ;-)
# You need to change the path here 
# Get a sorted list of all files in the sampled data set. Adjust the path of the dataset as necessary
files = sorted(glob.glob("/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/*.csv"))

In [9]:
files

['/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-01.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-02.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-03.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-04.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-05.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-06.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-07.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-08.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-09.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-10.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-11.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-12.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-01.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-02.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-03.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-04.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-05.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-06.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-07.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-08.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-09.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-10.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-11.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-12.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-01.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-02.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-03.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-04.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-05.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-06.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-07.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-08.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-09.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-10.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-11.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-12.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-01.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-02.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-03.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-04.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-05.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-06.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-07.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-08.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-09.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-10.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-11.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-12.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-01.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-02.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-03.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-04.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-05.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-06.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-07.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-08.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-09.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-10.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-11.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhvhv_tripdata_2019-02.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhvhv_tripdata_2019-03.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhvhv_tripdata_2019-04.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhvhv_tripdata_2019-05.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhvhv_tripdata_2019-06.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2013-08.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2013-09.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2013-10.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2013-11.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2013-12.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2014-01.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2014-02.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2014-03.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2014-04.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2014-05.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2014-06.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2014-07.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2014-08.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2014-09.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2014-10.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2014-11.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2014-12.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2015-01.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2015-02.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2015-03.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2015-04.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2015-05.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2015-06.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2015-07.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2015-08.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2015-09.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2015-10.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2015-11.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2015-12.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2016-01.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2016-02.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2016-03.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2016-04.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2016-05.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2016-06.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2016-07.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2016-08.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2016-09.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2016-10.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2016-11.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2016-12.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2017-01.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2017-02.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2017-03.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2017-04.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2017-05.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2017-06.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2017-07.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2017-08.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2017-09.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2017-10.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2017-11.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2017-12.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2018-01.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2018-02.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2018-03.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2018-04.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2018-05.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2018-06.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2018-07.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2018-08.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2018-09.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2018-10.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2018-11.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2018-12.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2019-01.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2019-02.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2019-03.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2019-04.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2019-05.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2019-06.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2009-01.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2009-02.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2009-03.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2009-04.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2009-05.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2009-06.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2009-07.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2009-08.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2009-09.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2009-10.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2009-11.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2009-12.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2010-01.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2010-02.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2010-03.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2010-04.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2010-05.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2010-06.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2010-07.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2010-08.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2010-09.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2010-10.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2010-11.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2010-12.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2011-01.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2011-02.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2011-03.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2011-04.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2011-05.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2011-06.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2011-07.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2011-08.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2011-09.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2011-10.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2011-11.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2011-12.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2012-01.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2012-02.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2012-03.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2012-04.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2012-05.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2012-06.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2012-07.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2012-08.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2012-09.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2012-10.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2012-11.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2012-12.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2013-01.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2013-02.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2013-03.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2013-04.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2013-05.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2013-06.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2013-07.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2013-08.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2013-09.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2013-10.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2013-11.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2013-12.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2014-01.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2014-02.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2014-03.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2014-04.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2014-05.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2014-06.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2014-07.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2014-08.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2014-09.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2014-10.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2014-11.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2014-12.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2015-01.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2015-02.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2015-03.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2015-04.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2015-05.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2015-06.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2015-07.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2015-08.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2015-09.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2015-10.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2015-11.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2015-12.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2016-01.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2016-02.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2016-03.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2016-04.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2016-05.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2016-06.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2016-07.csv',
 '/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/yellow_tripdata_2016-08.csv',

In [7]:
# NOTE: this cell actually reads 14 GB of data, so be patient ;-)
# Compute the metadata for each such file, using the function that we introduced above
metadata = [ get_metadata(f) for f in files ]

In [8]:
metadata

[('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-01.csv',
  'fhv',
  2015,
  1,
  4126514,
  136556,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-02.csv',
  'fhv',
  2015,
  2,
  4712489,
  155514,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-03.csv',
  'fhv',
  2015,
  3,
  4922012,
  163232,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-04.csv',
  'fhv',
  2015,
  4,
  5845469,
  195182,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-05.csv',
  'fhv',
  2015,
  5,
  6434970,
  214016,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-06.csv',
  'fhv',
  2015,
  6,
  6374684,
  211923,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-07.csv',
  'fhv',
  2015,
  7,
  6618288,
  219067,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-08.csv',
  'fhv',
  2015,
  8,
  7920242,
  263166,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-09.csv',
  'fhv',
  2015,
  9,
  9917658,
  331737,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-10.csv',
  'fhv',
  2015,
  10,
  12887943,
  432396,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-11.csv',
  'fhv',
  2015,
  11,
  12501798,
  419514,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-12.csv',
  'fhv',
  2015,
  12,
  13123033,
  440043,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-01.csv',
  'fhv',
  2016,
  1,
  12996598,
  436641,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-02.csv',
  'fhv',
  2016,
  2,
  14126428,
  473675,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-03.csv',
  'fhv',
  2016,
  3,
  14461598,
  485055,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-04.csv',
  'fhv',
  2016,
  4,
  15237579,
  511128,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-05.csv',
  'fhv',
  2016,
  5,
  16157955,
  541885,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-06.csv',
  'fhv',
  2016,
  6,
  16171575,
  542729,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-07.csv',
  'fhv',
  2016,
  7,
  16573965,
  555113,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-08.csv',
  'fhv',
  2016,
  8,
  16849116,
  564428,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-09.csv',
  'fhv',
  2016,
  9,
  17607089,
  588649,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-10.csv',
  'fhv',
  2016,
  10,
  18984101,
  634988,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-11.csv',
  'fhv',
  2016,
  11,
  18657612,
  623987,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2016-12.csv',
  'fhv',
  2016,
  12,
  20783789,
  694646,
  ('dispatching_base_num', 'pickup_date', 'locationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-01.csv',
  'fhv',
  2017,
  1,
  21794429,
  682264,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-02.csv',
  'fhv',
  2017,
  2,
  21206267,
  663675,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-03.csv',
  'fhv',
  2017,
  3,
  25063499,
  784308,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-04.csv',
  'fhv',
  2017,
  4,
  23576133,
  737715,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-05.csv',
  'fhv',
  2017,
  5,
  24668801,
  769150,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-06.csv',
  'fhv',
  2017,
  6,
  40980515,
  766807,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-07.csv',
  'fhv',
  2017,
  7,
  52190466,
  783023,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-08.csv',
  'fhv',
  2017,
  8,
  52991486,
  794550,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-09.csv',
  'fhv',
  2017,
  9,
  55373146,
  830269,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-10.csv',
  'fhv',
  2017,
  10,
  59641475,
  893744,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-11.csv',
  'fhv',
  2017,
  11,
  60209655,
  901735,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2017-12.csv',
  'fhv',
  2017,
  12,
  66613404,
  997515,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-01.csv',
  'fhv',
  2018,
  1,
  69034569,
  989132,
  ('pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag',
   'dispatching_base_number',
   'dispatching_base_num')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-02.csv',
  'fhv',
  2018,
  2,
  67457739,
  966193,
  ('pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag',
   'dispatching_base_number',
   'dispatching_base_num')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-03.csv',
  'fhv',
  2018,
  3,
  76752386,
  1098635,
  ('pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag',
   'dispatching_base_number',
   'dispatching_base_num')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-04.csv',
  'fhv',
  2018,
  4,
  73569939,
  1051268,
  ('pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag',
   'dispatching_base_number',
   'dispatching_base_num')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-05.csv',
  'fhv',
  2018,
  5,
  75336063,
  1077181,
  ('pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag',
   'dispatching_base_number',
   'dispatching_base_num')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-06.csv',
  'fhv',
  2018,
  6,
  73841386,
  1055642,
  ('pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag',
   'dispatching_base_number',
   'dispatching_base_num')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-07.csv',
  'fhv',
  2018,
  7,
  75564418,
  1078970,
  ('pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag',
   'dispatching_base_number',
   'dispatching_base_num')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-08.csv',
  'fhv',
  2018,
  8,
  77387505,
  1104867,
  ('pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag',
   'dispatching_base_number',
   'dispatching_base_num')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-09.csv',
  'fhv',
  2018,
  9,
  77508661,
  1106530,
  ('pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag',
   'dispatching_base_number',
   'dispatching_base_num')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-10.csv',
  'fhv',
  2018,
  10,
  81518808,
  1163490,
  ('pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag',
   'dispatching_base_number',
   'dispatching_base_num')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-11.csv',
  'fhv',
  2018,
  11,
  80051169,
  1142629,
  ('pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag',
   'dispatching_base_number',
   'dispatching_base_num')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2018-12.csv',
  'fhv',
  2018,
  12,
  83483022,
  1191813,
  ('pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag',
   'dispatching_base_number',
   'dispatching_base_num')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-01.csv',
  'fhv',
  2019,
  1,
  63877397,
  1155396,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-02.csv',
  'fhv',
  2019,
  2,
  4732899,
  84664,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-03.csv',
  'fhv',
  2019,
  3,
  3689797,
  65971,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-04.csv',
  'fhv',
  2019,
  4,
  5293797,
  94714,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-05.csv',
  'fhv',
  2019,
  5,
  5663928,
  101337,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-06.csv',
  'fhv',
  2019,
  6,
  5454490,
  97607,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-07.csv',
  'fhv',
  2019,
  7,
  5291503,
  94843,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-08.csv',
  'fhv',
  2019,
  8,
  5064314,
  90998,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-09.csv',
  'fhv',
  2019,
  9,
  2884698,
  51875,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-10.csv',
  'fhv',
  2019,
  10,
  5009611,
  90107,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2019-11.csv',
  'fhv',
  2019,
  11,
  4520192,
  81312,
  ('dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhvhv_tripdata_2019-02.csv',
  'fhvhv',
  2019,
  2,
  62947754,
  1007262,
  ('hvfhs_license_num',
   'dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhvhv_tripdata_2019-03.csv',
  'fhvhv',
  2019,
  3,
  74471634,
  1192596,
  ('hvfhs_license_num',
   'dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhvhv_tripdata_2019-04.csv',
  'fhvhv',
  2019,
  4,
  67782053,
  1085520,
  ('hvfhs_license_num',
   'dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhvhv_tripdata_2019-05.csv',
  'fhvhv',
  2019,
  5,
  69620812,
  1115337,
  ('hvfhs_license_num',
   'dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhvhv_tripdata_2019-06.csv',
  'fhvhv',
  2019,
  6,
  65453504,
  1049133,
  ('hvfhs_license_num',
   'dispatching_base_num',
   'pickup_datetime',
   'dropoff_datetime',
   'pulocationid',
   'dolocationid',
   'sr_flag')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2013-08.csv',
  'green',
  2013,
  8,
  57874,
  390,
  ('vendorid',
   'lpep_pickup_datetime',
   'lpep_dropoff_datetime',
   'store_and_fwd_flag',
   'ratecodeid',
   'pickup_longitude',
   'pickup_latitude',
   'dropoff_longitude',
   'dropoff_latitude',
   'passenger_count',
   'trip_distance',
   'fare_amount',
   'extra',
   'mta_tax',
   'tip_amount',
   'tolls_amount',
   'ehail_fee',
   'total_amount',
   'payment_type',
   'trip_type')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2013-09.csv',
  'green',
  2013,
  9,
  379901,
  2472,
  ('vendorid',
   'lpep_pickup_datetime',
   'lpep_dropoff_datetime',
   'store_and_fwd_flag',
   'ratecodeid',
   'pickup_longitude',
   'pickup_latitude',
   'dropoff_longitude',
   'dropoff_latitude',
   'passenger_count',
   'trip_distance',
   'fare_amount',
   'extra',
   'mta_tax',
   'tip_amount',
   'tolls_amount',
   'ehail_fee',
   'total_amount',
   'payment_type',
   'trip_type')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2013-10.csv',
  'green',
  2013,
  10,
  1303216,
  8453,
  ('vendorid',
   'lpep_pickup_datetime',
   'lpep_dropoff_datetime',
   'store_and_fwd_flag',
   'ratecodeid',
   'pickup_longitude',
   'pickup_latitude',
   'dropoff_longitude',
   'dropoff_latitude',
   'passenger_count',
   'trip_distance',
   'fare_amount',
   'extra',
   'mta_tax',
   'tip_amount',
   'tolls_amount',
   'ehail_fee',
   'total_amount',
   'payment_type',
   'trip_type')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2013-11.csv',
  'green',
  2013,
  11,
  2918797,
  18908,
  ('vendorid',
   'lpep_pickup_datetime',
   'lpep_dropoff_datetime',
   'store_and_fwd_flag',
   'ratecodeid',
   'pickup_longitude',
   'pickup_latitude',
   'dropoff_longitude',
   'dropoff_latitude',
   'passenger_count',
   'trip_distance',
   'fare_amount',
   'extra',
   'mta_tax',
   'tip_amount',
   'tolls_amount',
   'ehail_fee',
   'total_amount',
   'payment_type',
   'trip_type')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2013-12.csv',
  'green',
  2013,
  12,
  4588627,
  29734,
  ('vendorid',
   'lpep_pickup_datetime',
   'lpep_dropoff_datetime',
   'store_and_fwd_flag',
   'ratecodeid',
   'pickup_longitude',
   'pickup_latitude',
   'dropoff_longitude',
   'dropoff_latitude',
   'passenger_count',
   'trip_distance',
   'fare_amount',
   'extra',
   'mta_tax',
   'tip_amount',
   'tolls_amount',
   'ehail_fee',
   'total_amount',
   'payment_type',
   'trip_type')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2014-01.csv',
  'green',
  2014,
  1,
  6120938,
  39661,
  ('vendorid',
   'lpep_pickup_datetime',
   'lpep_dropoff_datetime',
   'store_and_fwd_flag',
   'ratecodeid',
   'pickup_longitude',
   'pickup_latitude',
   'dropoff_longitude',
   'dropoff_latitude',
   'passenger_count',
   'trip_distance',
   'fare_amount',
   'extra',
   'mta_tax',
   'tip_amount',
   'tolls_amount',
   'ehail_fee',
   'total_amount',
   'payment_type',
   'trip_type')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2014-02.csv',
  'green',
  2014,
  2,
  7692380,
  49687,
  ('vendorid',
   'lpep_pickup_datetime',
   'lpep_dropoff_datetime',
   'store_and_fwd_flag',
   'ratecodeid',
   'pickup_longitude',
   'pickup_latitude',
   'dropoff_longitude',
   'dropoff_latitude',
   'passenger_count',
   'trip_distance',
   'fare_amount',
   'extra',
   'mta_tax',
   'tip_amount',
   'tolls_amount',
   'ehail_fee',
   'total_amount',
   'payment_type',
   'trip_type')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2014-03.csv',
  'green',
  2014,
  3,
  9970310,
  64219,
  ('vendorid',
   'lpep_pickup_datetime',
   'lpep_dropoff_datetime',
   'store_and_fwd_flag',
   'ratecodeid',
   'pickup_longitude',
   'pickup_latitude',
   'dropoff_longitude',
   'dropoff_latitude',
   'passenger_count',
   'trip_distance',
   'fare_amount',
   'extra',
   'mta_tax',
   'tip_amount',
   'tolls_amount',
   'ehail_fee',
   'total_amount',
   'payment_type',
   'trip_type')),
 ('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/green_tripdata_2014-04.csv',
  'green',
  2014,
  4,
  10094619,
  64917,
  ('vendorid',
   'lpep_pickup_datetime',
   'lpep_dropoff_datetime',
   'store_and_fwd_flag',
   'ratecodeid',
   'pickup_longitude',
   'pickup_latitude',
   'dropoff_longitude',
   'dropoff_latitude',
   'passenger_count',
   'trip_distance',
   'fare_amount',
   'extra',
   'mta_tax',
   'tip_amount',
   'tolls_amount',
   'ehail_fee',
   'total_amount',
   'payment_type',

In [9]:
#pd.set_option('display.max_colwidth', 250)


# Put the metadata in a Pandas dataframe
metadata_labels = [ 'filename',  'type', 'year', 'month', 'size', 'num_records', 'schema']
df = pd.DataFrame.from_records(metadata, columns=metadata_labels)
df

,filename,type,year,month,size,num_records,schema
0,/home/marlene/Documents/ULB/CFDS/Final_Project...,fhv,2015,1,4126514,136556,"(dispatching_base_num, pickup_date, locationid)"
1,/home/marlene/Documents/ULB/CFDS/Final_Project...,fhv,2015,2,4712489,155514,"(dispatching_base_num, pickup_date, locationid)"
2,/home/marlene/Documents/ULB/CFDS/Final_Project...,fhv,2015,3,4922012,163232,"(dispatching_base_num, pickup_date, locationid)"
3,/home/marlene/Documents/ULB/CFDS/Final_Project...,fhv,2015,4,5845469,195182,"(dispatching_base_num, pickup_date, locationid)"
4,/home/marlene/Documents/ULB/CFDS/Final_Project...,fhv,2015,5,6434970,214016,"(dispatching_base_num, pickup_date, locationid)"
...,...,...,...,...,...,...,...
256,/home/marlene/Documents/ULB/CFDS/Final_Project...,yellow,2019,2,32109751,350590,"(vendorid, tpep_pickup_datetime, tpep_dropoff_..."
257,/home/marlene/Documents/ULB/CFDS/Final_Project...,yellow,2019,3,35856704,390942,"(vendorid, tpep_pickup_datetime, tpep_dropoff_..."
258,/home/marlene/Documents/ULB/CFDS/Final_Project...,yellow,2019,4,34046518,371197,"(vendorid, tpep_pickup_datetime, tpep_dropoff_..."
259,/home/marlene/Documents/ULB/CFDS/Final_Project...,yellow,2019,5,34643823,377704,"(vendorid, tpep_pickup_datetime, tpep_dropoff_..."
260,/home/marlene/Documents/ULB/CFDS/Final_Project...,yellow,2019,6,31795331,346739,"(vendorid, tpep_pickup_datetime, tpep_dropoff_..."

In [10]:
# Save the dataframe for future use (e.g., in later stages)
df.to_csv('/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/dataset-description.csv')

In [14]:
# You can use the `describe` function of a Pandas Series to get the basic statistics
df['size'].describe()

count    2.610000e+02
mean     5.699806e+07
std      5.040927e+07
min      5.787400e+04
25%      1.033738e+07
50%      4.048584e+07
75%      1.111178e+08
max      1.489577e+08
Name: size, dtype: float64

In [15]:
# You can use the `describe` function of a Pandas Series to get the basic statistics
df.describe()

              year       month          size   num_records
count   261.000000  261.000000  2.610000e+02  2.610000e+02
mean   2015.206897    6.360153  5.699806e+07  4.685906e+05
std       2.818092    3.441906  5.040927e+07  3.284080e+05
min    2009.000000    1.000000  5.787400e+04  3.900000e+02
25%    2014.000000    3.000000  1.033738e+07  7.821900e+04
50%    2016.000000    6.000000  4.048584e+07  5.147450e+05
75%    2017.000000    9.000000  1.111178e+08  7.192930e+05
max    2019.000000   12.000000  1.489577e+08  1.192596e+06

In [16]:
# TODO: get the same kind of information about the number of records here.
df['num_records'].describe()

count    2.610000e+02
mean     4.685906e+05
std      3.284080e+05
min      3.900000e+02
25%      7.821900e+04
50%      5.147450e+05
75%      7.192930e+05
max      1.192596e+06
Name: num_records, dtype: float64

Take the time to inspect the numbers you got above, so that you get an impression of the order of magnitude of files in the dataset. Write this down in your own words

**Conclusion:**

## Analysis of the schema evolution.

Over time, the relational schema associated to each type of trip data (yellow, green, fhv, hvfhv) has changed. Let us analyze the changes.

In [11]:
# Code to help analyze the schema changes goes here

# NOTE: What follows is *a* possible way of doing this. You may have a different way.
# Solution approach:
#   Given a pandas dataframe that contains all the files + their metadata of a single sub-dataset
#   let us create a new dataframe that adds two dataframe columns containing, respectively:
#      (1) the schema columns that were removed since the previous file; and 
#      (2) the schema columns added since the previous file

# You need to complete the  analyze_schema_changes function below !

def diff_schema(schema1, schema2):
    ''' Compute a tuple containing all elements of schema1 that are not in schema2        
    
        Example: if  schema1= ("a", "b", "c") and schema2 = ("b", "d", "e") the result = ("a", "c")
    '''
    lschema1 = list(schema1) # schema1 is a tuple, convert it to a list
    lschema2 = list(schema2) # schema2 is a tuple, convert it to a list
    removed = [ x for x in lschema1 if x not in lschema2 ]
    return tuple(removed) # removed is a list, convert it back to a tuple
    

def analyze_schema_changes(dataset):
    '''Analyze schema changes over time for all files in the dataset
    
    dataset: A dataframe that lists all files beloning to a given sub-dataset (fhv, yellow, green, ...)
             with their metadata, sorted lexicographically on (year, month)
    
    output: a dataframe that contains for each file two extra columns: removed, and added containing 
    '''
  
    prev_schema = () # assume the initial schema is empty
    labels = ['type', 'year', 'month',  'schema', 'removed', 'added'] # The column labels of the resulting dataframe

    # Solution approach: 
    dataset = dataset.sort_values(by=['year', 'month'])
    removed = []  # list of columns removed
    added = []  # list of columns added

    for row in range(len(dataset)):
        a = dataset.iloc[row]['schema']
        b = dataset.iloc[row-1]['schema']
        if row != 0:
            rm = diff_schema(b,a)
            ad = diff_schema(a,b)
        else:
            rm = prev_schema
            ad = prev_schema

        removed.append(rm)
        added.append(ad)
    dataset['removed'] = removed
    dataset['added'] = added

    # convert the result list to the dataframe
    return pd.DataFrame(dataset, columns=labels)

### Analysis of schema changes for fhv cab data files

Analyze the schema changes for the FHV cab data files. Write down your conclusions

In [16]:
# Compute the dataframe containing all files belonging to the fhv dataset
fhv_files = df[ df['type'] == 'fhv']
fhv_files.head()

,filename,type,year,month,size,num_records,schema
0,/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-01.csv,fhv,2015,1,4126514,136556,"(dispatching_base_num, pickup_date, locationid)"
1,/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-02.csv,fhv,2015,2,4712489,155514,"(dispatching_base_num, pickup_date, locationid)"
2,/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-03.csv,fhv,2015,3,4922012,163232,"(dispatching_base_num, pickup_date, locationid)"
3,/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-04.csv,fhv,2015,4,5845469,195182,"(dispatching_base_num, pickup_date, locationid)"
4,/home/marlene/Documents/ULB/CFDS/Final_Project_CFDS/data/fhv_tripdata_2015-05.csv,fhv,2015,5,6434970,214016,"(dispatching_base_num, pickup_date, locationid)"

In [135]:
# Analyze the schema changes
fhv_changes = analyze_schema_changes(fhv_files)
fhv_changes

,type,year,month,schema,removed,added
0,fhv,2015,1,"(dispatching_base_num, pickup_date, locationid)",(),()
1,fhv,2015,2,"(dispatching_base_num, pickup_date, locationid)",(),()
2,fhv,2015,3,"(dispatching_base_num, pickup_date, locationid)",(),()
3,fhv,2015,4,"(dispatching_base_num, pickup_date, locationid)",(),()
4,fhv,2015,5,"(dispatching_base_num, pickup_date, locationid)",(),()
5,fhv,2015,6,"(dispatching_base_num, pickup_date, locationid)",(),()
6,fhv,2015,7,"(dispatching_base_num, pickup_date, locationid)",(),()
7,fhv,2015,8,"(dispatching_base_num, pickup_date, locationid)",(),()
8,fhv,2015,9,"(dispatching_base_num, pickup_date, locationid)",(),()
9,fhv,2015,10,"(dispatching_base_num, pickup_date, locationid)",(),()
10,fhv,2015,11,"(dispatching_base_num, pickup_date, locationid)",(),()
11,fhv,2015,12,"(dispatching_base_num, pickup_date, locationid)",(),()
12,fhv,2016,1,"(dispatching_base_num, pickup_date, locationid)",(),()
13,fhv,2016,2,"(dispatching_base_num, pickup_date, locationid)",(),()
14,fhv,2016,3,"(dispatching_base_num, pickup_date, locationid)",(),()
15,fhv,2016,4,"(dispatching_base_num, pickup_date, locationid)",(),()
16,fhv,2016,5,"(dispatching_base_num, pickup_date, locationid)",(),()
17,fhv,2016,6,"(dispatching_base_num, pickup_date, locationid)",(),()
18,fhv,2016,7,"(dispatching_base_num, pickup_date, locationid)",(),()
19,fhv,2016,8,"(dispatching_base_num, pickup_date, locationid)",(),()
20,fhv,2016,9,"(dispatching_base_num, pickup_date, locationid)",(),()
21,fhv,2016,10,"(dispatching_base_num, pickup_date, locationid)",(),()
22,fhv,2016,11,"(dispatching_base_num, pickup_date, locationid)",(),()
23,fhv,2016,12,"(dispatching_base_num, pickup_date, locationid)",(),()
24,fhv,2017,1,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid)","(pickup_date, locationid)","(pickup_datetime, dropoff_datetime, pulocationid, dolocationid)"
25,fhv,2017,2,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid)",(),()
26,fhv,2017,3,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid)",(),()
27,fhv,2017,4,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid)",(),()
28,fhv,2017,5,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid)",(),()
29,fhv,2017,6,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid)",(),()
30,fhv,2017,7,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),"(sr_flag,)"
31,fhv,2017,8,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),()
32,fhv,2017,9,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),()
33,fhv,2017,10,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),()
34,fhv,2017,11,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),()
35,fhv,2017,12,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),()
36,fhv,2018,1,"(pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag, dispatching_base_number, dispatching_base_num)",(),"(dispatching_base_number,)"
37,fhv,2018,2,"(pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag, dispatching_base_number, dispatching_base_num)",(),()
38,fhv,2018,3,"(pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag, dispatching_base_number, dispatching_base_num)",(),()
39,fhv,2018,4,"(pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag, dispatching_base_number, dispatching_base_num)",(),()
40,fhv,2018,5,"(pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag, dispatching_base_number, dispatching_base_num)",(),()
41,fhv,2018,6,"(pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag, dispatching_base_number, dispatching_base_num)",(),()
42,fhv,2018,7,"(pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag, dispatching_base_number, dispatching_base_num)",(),()
43,fhv,2018,8,"(pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag, dispatching_base_number, dispatching_base_num)",(),()
44,fhv,2018,9,"(pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag, dispatching_base_number, dispatching_base_num)",(),()
45,fhv,2018,10,"(pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag, dispatching_base_number, dispatching_base_num)",(),()
46,fhv,2018,11,"(pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag, dispatching_base_number, dispatching_base_num)",(),()
47,fhv,2018,12,"(pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag, dispatching_base_number, dispatching_base_num)",(),()
48,fhv,2019,1,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)","(dispatching_base_number,)",()
49,fhv,2019,2,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),()
50,fhv,2019,3,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),()
51,fhv,2019,4,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),()
52,fhv,2019,5,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),()
53,fhv,2019,6,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),()
54,fhv,2019,7,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),()
55,fhv,2019,8,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),()
56,fhv,2019,9,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),()
57,fhv,2019,10,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),()
58,fhv,2019,11,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),()

In [136]:
# fhv_changes has one row for each file in the fhv dataset
# The rows where nothing changes are actually not interesting
# Let us focus on only those lines where something is added or removed
fhv_delta = fhv_changes[(fhv_changes['added'] != ()) |  (fhv_changes['removed'] != ())]
fhv_delta

,type,year,month,schema,removed,added
24,fhv,2017,1,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid)","(pickup_date, locationid)","(pickup_datetime, dropoff_datetime, pulocationid, dolocationid)"
30,fhv,2017,7,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),"(sr_flag,)"
36,fhv,2018,1,"(pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag, dispatching_base_number, dispatching_base_num)",(),"(dispatching_base_number,)"
48,fhv,2019,1,"(dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)","(dispatching_base_number,)",()

Now inspect fhv_delta further, line by line, and describe what the changes are

### Conclusion for fhv data files

**From 2015.01 to 2016.12** we have (dispatching_base_num, pickup_date, locationid) as schema <br>
**In 2017.01** columns (pickup_date, locationid) were removed and columns (pickup_datetime, dropoff_datetime, pulocationid, dolocationid) <br> were added <br>
**In 2017.07**  column (sr_flag) was added. <br>
**In 2018.01**  column (dispatching_base_number,) was added.  <br>
**In 2019.01**  column (dispatching_base_number,) was removed.  <br>

### Analysis of schema changes for fhvhv data files

Analyze the schema changes for the FHV cab data files. Write down your conclusions

In [142]:
# Compute the dataframe containing all files belonging to the fhv dataset
fhvhv_files = df[ df['type'] == 'fhvhv']
fhvhv_files 
# Analyze the schema changes
fhvhv_changes = analyze_schema_changes(fhvhv_files)
fhvhv_changes

,type,year,month,schema,removed,added
59,fhvhv,2019,2,"(hvfhs_license_num, dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),()
60,fhvhv,2019,3,"(hvfhs_license_num, dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),()
61,fhvhv,2019,4,"(hvfhs_license_num, dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),()
62,fhvhv,2019,5,"(hvfhs_license_num, dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),()
63,fhvhv,2019,6,"(hvfhs_license_num, dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)",(),()

In [34]:
len(fhvhv_files)

5

### Conclusion for fhvhv data files

**From 2019.02 to 2019.06** the schema remains the same: <br>
(hvfhs_license_num, dispatching_base_num, pickup_datetime, dropoff_datetime, pulocationid, dolocationid, sr_flag)

### Analysis of schema changes for green cab data files

Analyze the schema changes for the green taxi data files. Write down your conclusions

In [12]:
pd.set_option('display.max_colwidth', 350)
pd.set_option('display.max_row', 71)
# Compute the dataframe containing all files belonging to the fhv dataset
green_files = df[ df['type'] == 'green']
green_files
# Analyze the schema changes
green_changes = analyze_schema_changes(green_files)
green_changes

,type,year,month,schema,removed,added
64,green,2013,8,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, total_amount, payment_type, trip_type)",(),()
65,green,2013,9,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, total_amount, payment_type, trip_type)",(),()
66,green,2013,10,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, total_amount, payment_type, trip_type)",(),()
67,green,2013,11,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, total_amount, payment_type, trip_type)",(),()
68,green,2013,12,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, total_amount, payment_type, trip_type)",(),()
69,green,2014,1,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, total_amount, payment_type, trip_type)",(),()
70,green,2014,2,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, total_amount, payment_type, trip_type)",(),()
71,green,2014,3,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, total_amount, payment_type, trip_type)",(),()
72,green,2014,4,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, total_amount, payment_type, trip_type)",(),()
73,green,2014,5,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, total_amount, payment_type, trip_type)",(),()
74,green,2014,6,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, total_amount, payment_type, trip_type)",(),()
75,green,2014,7,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, total_amount, payment_type, trip_type)",(),()
76,green,2014,8,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, total_amount, payment_type, trip_type)",(),()
77,green,2014,9,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, total_amount, payment_type, trip_type)",(),()
78,green,2014,10,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, total_amount, payment_type, trip_type)",(),()
79,green,2014,11,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, total_amount, payment_type, trip_type)",(),()
80,green,2014,12,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, total_amount, payment_type, trip_type)",(),()
81,green,2015,1,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),"(improvement_surcharge,)"
82,green,2015,2,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
83,green,2015,3,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
84,green,2015,4,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
85,green,2015,5,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
86,green,2015,6,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
87,green,2015,7,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
88,green,2015,8,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
89,green,2015,9,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
90,green,2015,10,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
91,green,2015,11,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
92,green,2015,12,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
93,green,2016,1,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
94,green,2016,2,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
95,green,2016,3,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
96,green,2016,4,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
97,green,2016,5,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
98,green,2016,6,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
99,green,2016,7,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)","(pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude)","(pulocationid, dolocationid)"
100,green,2016,8,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
101,green,2016,9,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
102,green,2016,10,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
103,green,2016,11,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
104,green,2016,12,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
105,green,2017,1,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
106,green,2017,2,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
107,green,2017,3,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
108,green,2017,4,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
109,green,2017,5,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
110,green,2017,6,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
111,green,2017,7,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
112,green,2017,8,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
113,green,2017,9,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
114,green,2017,10,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
115,green,2017,11,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
116,green,2017,12,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
117,green,2018,1,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
118,green,2018,2,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
119,green,2018,3,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
120,green,2018,4,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
121,green,2018,5,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
122,green,2018,6,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
123,green,2018,7,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
124,green,2018,8,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()
125,green,2018,9,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),()

In [32]:
len(green_files)

71

In [13]:
green_delta = green_changes[(green_changes['added'] != ()) |  (green_changes['removed'] != ())]
green_delta

,type,year,month,schema,removed,added
81,green,2015,1,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)",(),"(improvement_surcharge,)"
99,green,2016,7,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type)","(pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude)","(pulocationid, dolocationid)"
129,green,2019,1,"(vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pulocationid, dolocationid, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, improvement_surcharge, total_amount, payment_type, trip_type, congestion_surcharge)",(),"(congestion_surcharge,)"

### Conclusion for green data files

**From 2013.08 to 2014.12** we have as schema: <br>
    (vendorid, lpep_pickup_datetime, lpep_dropoff_datetime, store_and_fwd_flag, ratecodeid, pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, trip_distance, fare_amount, extra, mta_tax, tip_amount, tolls_amount, ehail_fee, total_amount, payment_type, trip_type)
**In 2015.01**  columns (pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude) were removed and 
columns (pulocationid, dolocationid) were added. <br>
**In 2019.01**  column (congestion_surcharge,) was added.  <br>

### Analysis of schema changes for yellow cab data files

Analyze the schema changes for the Yellow taxi data files. Write down your conclusions

In [144]:
# Compute the dataframe containing all files belonging to the fhv dataset
yellow_files = df[ df['type'] == 'yellow']
yellow_files
# Analyze the schema changes
yellow_changes = analyze_schema_changes(yellow_files)
yellow_changes

,type,year,month,schema,removed,added
135,yellow,2009,1,"(vendor_name, trip_pickup_datetime, trip_dropoff_datetime, passenger_count, trip_distance, start_lon, start_lat, rate_code, store_and_forward, end_lon, end_lat, payment_type, fare_amt, surcharge, mta_tax, tip_amt, tolls_amt, total_amt)",(),()
136,yellow,2009,2,"(vendor_name, trip_pickup_datetime, trip_dropoff_datetime, passenger_count, trip_distance, start_lon, start_lat, rate_code, store_and_forward, end_lon, end_lat, payment_type, fare_amt, surcharge, mta_tax, tip_amt, tolls_amt, total_amt)",(),()
137,yellow,2009,3,"(vendor_name, trip_pickup_datetime, trip_dropoff_datetime, passenger_count, trip_distance, start_lon, start_lat, rate_code, store_and_forward, end_lon, end_lat, payment_type, fare_amt, surcharge, mta_tax, tip_amt, tolls_amt, total_amt)",(),()
138,yellow,2009,4,"(vendor_name, trip_pickup_datetime, trip_dropoff_datetime, passenger_count, trip_distance, start_lon, start_lat, rate_code, store_and_forward, end_lon, end_lat, payment_type, fare_amt, surcharge, mta_tax, tip_amt, tolls_amt, total_amt)",(),()
139,yellow,2009,5,"(vendor_name, trip_pickup_datetime, trip_dropoff_datetime, passenger_count, trip_distance, start_lon, start_lat, rate_code, store_and_forward, end_lon, end_lat, payment_type, fare_amt, surcharge, mta_tax, tip_amt, tolls_amt, total_amt)",(),()
140,yellow,2009,6,"(vendor_name, trip_pickup_datetime, trip_dropoff_datetime, passenger_count, trip_distance, start_lon, start_lat, rate_code, store_and_forward, end_lon, end_lat, payment_type, fare_amt, surcharge, mta_tax, tip_amt, tolls_amt, total_amt)",(),()
141,yellow,2009,7,"(vendor_name, trip_pickup_datetime, trip_dropoff_datetime, passenger_count, trip_distance, start_lon, start_lat, rate_code, store_and_forward, end_lon, end_lat, payment_type, fare_amt, surcharge, mta_tax, tip_amt, tolls_amt, total_amt)",(),()
142,yellow,2009,8,"(vendor_name, trip_pickup_datetime, trip_dropoff_datetime, passenger_count, trip_distance, start_lon, start_lat, rate_code, store_and_forward, end_lon, end_lat, payment_type, fare_amt, surcharge, mta_tax, tip_amt, tolls_amt, total_amt)",(),()
143,yellow,2009,9,"(vendor_name, trip_pickup_datetime, trip_dropoff_datetime, passenger_count, trip_distance, start_lon, start_lat, rate_code, store_and_forward, end_lon, end_lat, payment_type, fare_amt, surcharge, mta_tax, tip_amt, tolls_amt, total_amt)",(),()
144,yellow,2009,10,"(vendor_name, trip_pickup_datetime, trip_dropoff_datetime, passenger_count, trip_distance, start_lon, start_lat, rate_code, store_and_forward, end_lon, end_lat, payment_type, fare_amt, surcharge, mta_tax, tip_amt, tolls_amt, total_amt)",(),()
145,yellow,2009,11,"(vendor_name, trip_pickup_datetime, trip_dropoff_datetime, passenger_count, trip_distance, start_lon, start_lat, rate_code, store_and_forward, end_lon, end_lat, payment_type, fare_amt, surcharge, mta_tax, tip_amt, tolls_amt, total_amt)",(),()
146,yellow,2009,12,"(vendor_name, trip_pickup_datetime, trip_dropoff_datetime, passenger_count, trip_distance, start_lon, start_lat, rate_code, store_and_forward, end_lon, end_lat, payment_type, fare_amt, surcharge, mta_tax, tip_amt, tolls_amt, total_amt)",(),()
147,yellow,2010,1,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...","(vendor_name, trip_pickup_datetime, trip_dropoff_datetime, start_lon, start_lat, store_and_forward, end_lon, end_lat, fare_amt, tip_amt, tolls_amt, total_amt)","(vendor_id, pickup_datetime, dropoff_datetime, pickup_longitude, pickup_latitude, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, fare_amount, tip_amount, tolls_amount, total_amount)"
148,yellow,2010,2,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
149,yellow,2010,3,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
150,yellow,2010,4,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
151,yellow,2010,5,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
152,yellow,2010,6,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
153,yellow,2010,7,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
154,yellow,2010,8,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
155,yellow,2010,9,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
156,yellow,2010,10,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
157,yellow,2010,11,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
158,yellow,2010,12,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
159,yellow,2011,1,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
160,yellow,2011,2,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
161,yellow,2011,3,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
162,yellow,2011,4,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
163,yellow,2011,5,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
164,yellow,2011,6,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
165,yellow,2011,7,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
166,yellow,2011,8,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
167,yellow,2011,9,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
168,yellow,2011,10,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
169,yellow,2011,11,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
170,yellow,2011,12,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
171,yellow,2012,1,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
172,yellow,2012,2,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
173,yellow,2012,3,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
174,yellow,2012,4,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
175,yellow,2012,5,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
176,yellow,2012,6,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
177,yellow,2012,7,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
178,yellow,2012,8,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
179,yellow,2012,9,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
180,yellow,2012,10,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
181,yellow,2012,11,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
182,yellow,2012,12,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
183,yellow,2013,1,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
184,yellow,2013,2,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
185,yellow,2013,3,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
186,yellow,2013,4,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
187,yellow,2013,5,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
188,yellow,2013,6,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
189,yellow,2013,7,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
190,yellow,2013,8,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
191,yellow,2013,9,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
192,yellow,2013,10,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
193,yellow,2013,11,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
194,yellow,2013,12,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
195,yellow,2014,1,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
196,yellow,2014,2,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
197,yellow,2014,3,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
198,yellow,2014,4,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
199,yellow,2014,5,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
200,yellow,2014,6,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
201,yellow,2014,7,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
202,yellow,2014,8,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
203,yellow,2014,9,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
204,yellow,2014,10,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()
205,yellow,2014,11,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...",(),()

In [145]:
len(yellow_files)

126

In [146]:
yellow_delta = yellow_changes[(yellow_changes['added'] != ()) |  (yellow_changes['removed'] != ())]
yellow_delta

,type,year,month,schema,removed,added
147,yellow,2010,1,"(vendor_id, pickup_datetime, dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, rate_code, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, surcharge, mta_tax, tip_amount, tolls...","(vendor_name, trip_pickup_datetime, trip_dropoff_datetime, start_lon, start_lat, store_and_forward, end_lon, end_lat, fare_amt, tip_amt, tolls_amt, total_amt)","(vendor_id, pickup_datetime, dropoff_datetime, pickup_longitude, pickup_latitude, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, fare_amount, tip_amount, tolls_amount, total_amount)"
207,yellow,2015,1,"(vendorid, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, pickup_longitude, pickup_latitude, ratecodeid, store_and_fwd_flag, dropoff_longitude, dropoff_latitude, payment_type, fare_amount, extra, mta_tax, tip_amount,...","(vendor_id, pickup_datetime, dropoff_datetime, rate_code, surcharge)","(vendorid, tpep_pickup_datetime, tpep_dropoff_datetime, ratecodeid, extra, improvement_surcharge)"
225,yellow,2016,7,"(vendorid, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, ratecodeid, store_and_fwd_flag, pulocationid, dolocationid, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_...","(pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude)","(pulocationid, dolocationid)"
255,yellow,2019,1,"(vendorid, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, ratecodeid, store_and_fwd_flag, pulocationid, dolocationid, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_...",(),"(congestion_surcharge,)"

### Conclusion for yellow data files

**From 2015.01 to 2016.12** we have (dispatching_base_num, pickup_date, locationid) as schema <br>
**In 2017.07**  column (sr_flag) was added. <br>
**In 2018.01**  column (dispatching_base_number,) was added.  <br>
**In 2019.01**  column (dispatching_base_number,) was removed.  <br>